--Task table
CREATE TABLE TASK (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      short_desc varchar(255) not null,
                      details text,
                      start_date date not null,
                      end_date date
);

create sequence task_sequence start with 1 increment by 1;

insert into "TASK" (short_desc, details, start_date, end_date)
values ('Test task description', 'This is test details', '2024-03-15', '2024-03-18');