--Task table
CREATE TABLE task (
                      tid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      group_id BIGINT,
                      short_desc varchar(255) not null,
                      details text,
                      start_date date not null,
                      end_date date
);

create sequence task_sequence start with 2 increment by 1;

insert into task ( group_id, short_desc, details, start_date, end_date)
values ( 1, 'Test task description', 'This is test details', '2024-03-15', '2024-03-18');

CREATE TABLE task_group
(
    tid      bigint REFERENCES TASK (tid),
    group_id BIGINT REFERENCES "group" (id)
);

insert into task_group(tid, group_id)
values (1,1);

